### ISSUE TITLE
Missing library libcurl when executing rake tasks

### ISSUE THREAD

**Issue by AxelTerizaki** [mnyrop/wax_tasks#70]
**Describe the bug**
I've tried to install wax_tasks on Windows but am getting an error about libcurl missing when trying to launch a pagemaster task on a collection.

I suppose this is not wax_tasks fault but I'd like to know what I need to do and why it does need libcurl. I suppose this problem doesn't occur at all on a Linux system for example.

**To Reproduce**
1. Install wax_tasks on Windows
2. Create a collection in _config.yml
3. Run the pagemaster task on it

**Expected behavior**
Should just work ^^

**Screenshots**
```$ bundle exec rake wax:pagemaster collections/fr/creators
rake aborted!
LoadError: Could not open library 'libcurl': Le module sp▒cifi▒ est introuvable.
.
Could not open library 'libcurl.dll': Le module sp▒cifi▒ est introuvable.
.
Could not open library 'libcurl.so.4': Le module sp▒cifi▒ est introuvable.
.
Could not open library 'libcurl.so.4.dll': Le module sp▒cifi▒ est introuvable.
D:/perso/karaokemugen-website/Rakefile:2:in `load'
D:/perso/karaokemugen-website/Rakefile:2:in `block in <top (required)>'
D:/perso/karaokemugen-website/Rakefile:2:in `each'
D:/perso/karaokemugen-website/Rakefile:2:in `<top (required)>'
```

**Desktop (please complete the following information):**
 - OS: Windows 7

**Additional context**
Using bundler 1.15.4 and ruby 2.4.1p111

**Comment by mnyrop** [comment]
`wax_tasks` and quite a few other Jekyll adjacent gems rely on [`typhoeus`](https://github.com/typhoeus/typhoeus), which wraps Ruby bindings around `libcurl`. I think `libcurl` either comes by default with *nix machines and/or its installed elsewhere in the Ruby process, but regardless it looks like Windows doesn't have/require it.

I can't test it right now (since I don't have a windows machine or vm available atm), but it looks like the steps in the following link are a good bet for setting up curl on windows 7:

<https://stackoverflow.com/questions/22525093/typhoeus-windows-installation>

Also, try putting the following in your site's Gemfile if you haven't already:

```
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "wdm", "~> 0.1.0" if Gem.win_platform?
```

Hope this helps!

**Comment by AxelTerizaki** [comment]
Hmmm, can't seem to work for some reason. I tried to add libcurl.dll to my path but I still get the same error.

I'll try to search around a bit more but it's weird it doesn't seem to work as expected from the stackoverflow link you provided.

**Comment by AxelTerizaki** [comment]
It seems impossible to use : when I try to install curl from the curl official website, I still get the same error.

if I use an older libcurl.dll from 2 years ago, FFI complains about a missing function in libcurl (so it really loads the dll file...)

I think I need a specific version of libcurl, but to know which one now >.>

**Comment by AxelTerizaki** [comment]
Okay, sorry for the spam, I found a DLL which seems to work (7.40).

I've seen similar issues with github-pages while doing my research on this specific issue, some projects did move back from Typhoeus to the basic Ruby http module to avoid this.
