### ISSUE TITLE
How to link to generated pages with spaces?

### ISSUE THREAD

**Issue by AxelTerizaki** [mnyrop/wax_tasks#74]
Hello.

This is more of a question than a bug report.

I've just tried generating pages and it seems to work fine. My PIDs however contain spaces, and they're replaced by the `_` character. However, the `slugify` liquid tag in Jekyll changes spaces to the `-` character.

Sure, I could try to replace spaces by `-` when creating my PIDs, but I thought it would be more consistent if wax_task:pagemaster did generate pages using the same slugification rules than Jekyll. Would make linking to pages more easier.

What do you think?

**Comment by AxelTerizaki** [comment]
I'm having trouble related to Jekyll this time (as the slugify liquid filter doesn't properly remove diacritics) so I'm going to open an issue there, but I was thinking : wouldn't it be best to write your own liquid filter that would render strings the same way you do when making them an URL?

The previous plugin I was using (https://github.com/avillafiorita/jekyll-datapage_gen) had its own (undocumented though) liquid filter to get the correct filename it generated when trying to link to an item.

**Comment by mnyrop** [comment]
I've thought about this a lot. My understanding is that hyphens can be fickle (they can secretly be unicode m-dashes or n-dashes). Since many of the use cases I'm trying to accommodate include data generated manually by novices, underscores are more consistent. 

As a note, you can also use the [liquid string replace filter](https://shopify.github.io/liquid/filters/replace/) instead of `slugify` for more control (e.g, `{{ "test pid num" | replace: " ", "_" }}`).
